# Generated by Django 5.1 on 2024-09-02 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='endereco',
            name='complemento',
            field=models.CharField(blank=True, default='Não especificado', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='endereco',
            name='logradouro',
            field=models.CharField(default='Não especificado', max_length=255),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='bairro',
            field=models.CharField(default='Não especificado', max_length=150),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='cep',
            field=models.CharField(default='00000-000', max_length=8),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='cidade',
            field=models.CharField(default='Não especificado', max_length=30),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='numero',
            field=models.CharField(default='S/N', max_length=10),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='uf',
            field=models.CharField(default='XX', max_length=2),
        ),
    ]
