# Generated by Django 5.1 on 2024-09-02 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0002_endereco_complemento_endereco_logradouro_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='endereco',
        ),
        migrations.DeleteModel(
            name='Endereco',
        ),
    ]
