# Generated by Django 5.1 on 2024-09-03 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Motorista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('matricula', models.CharField(max_length=20)),
                ('cnh', models.CharField(max_length=20)),
                ('cpf', models.CharField(max_length=11)),
                ('data_emissao', models.DateField()),
                ('data_validade', models.DateField()),
                ('categoria_cnh', models.CharField(max_length=11)),
            ],
        ),
    ]
